AWSTemplateFormatVersion: "2010-09-09"
Description: Resources needed to deploy Spotify project
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: sample
      Description: First AWS Lambda function
      Runtime: nodejs16.x
      Role: arn:aws:iam::770653768231:role/service-role/sample-role-5flu1nuj
      Handler: index.handler
      Code:
        S3Bucket: webscrape-spotify-bucket
        S3Key: "spotify-webscraper.zip"
      Timeout: 30
      MemorySize: 128
      TracingConfig:
        Mode: Active
  ScheduledRule:
    Type: AWS::Event::Rule
    DependsOn: LambdaFunction
    Properties:
      Name: webscrape-spotify-cloudwatch
      Description: "ScheduledRule"
      ScheduledExpression: "rate(5 minutes)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "LambdaFunction"
              - "Arn"
          Id: "TargetFunc"
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    DependsOn: LambdaFunction
    Properties:
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
